spring:
  datasource:
    url: jdbc:mysql://owu.linkpc.net/uwfapp
    username: uwfapp
    password: 19823366
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: sfhhfsfjs;lfjafhddslfhkhf'oifaopfikdsl;fhsa;fj'ksa'lfj;iafua'sf;j;
  access-token:
    ttl-millis: 6000000000
  refresh-token:
    ttl-millis: 70000000000

server:
  port: 8080